#!/bin/bash

output="$(checkupdates && yay -Qua)"

if [[ -z "$output" ]]; then
    text=""
    tooltip=""
else
    text="$(echo "$output" | wc -l)"

  if [[ $text -gt 30 ]]; then
    tooltip="$(echo "$output" | head -n 20 | sed ':a;N;$!ba;s/\n/\\n/g')"
    tooltip+='...'
  else
    tooltip="$(echo "$output" | sed ':a;N;$!ba;s/\n/\\n/g')"
  fi
fi

echo {\"text\":\"$text\", \"tooltip\":\"$tooltip\"}
exit 0
